[package]
name = "sardp"
version = "0.1.0"
edition = "2024"

[dependencies]
ciborium = "0.2.2"
ed25519-dalek = { version = "3.0.0", features = ["rand_core"] }
quinn = "0.11.11"
rand = "0.10.2"
rcgen = "0.14.9"
serde = { version = "1.0.229", features = ["derive"] }
serde_bytes = "0.11.19"
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time"] }

[lints.rust]
unsafe_code = "forbid"
